<?php
namespace StudentManagementSystem;

class Teacher extends Staffs {
   public $grade_id;
   public $subject_id;

   public function getName()
   {
       return parent::getName(); // TODO: Change the autogenerated stub
   }

   public function getId()
   {
       return parent::getId(); // TODO: Change the autogenerated stub
   }

   public function getSex()
   {
       return parent::getSex(); // TODO: Change the autogenerated stub
   }

   public function getSubjectId(){
       return $this->subject_id;
   }

   public function getGradeId(){
       return $this->grade_id;
   }
}

